services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tic2025
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: